language: python
python:
    - "3.6"
cache: pip
install:
    - pip install pipenv --upgrade
    - pipenv install --dev
script:
    - py.test
deploy:
    provider: heroku
    api_key:
        secure: db22a20d-bf86-4a4b-bbc7-9af89c8f36c6
